type: generic
vargs:
  word_dim: 400
  hidden_dim: 400
  word_emb_dropout: 0.1
  word_encoder:
    type: composite
    vargs:
      first_dim: 300
      second_dim: 100
      first:
        type: vzhong-embeddings
        vargs:
          freeze: true
          cls_name: GloveEmbedding
          default: zero
      second:
        type: vzhong-embeddings
        vargs:
          freeze: true
          cls_name: KazumaCharEmbedding
          default: zero
  dst_encoder:
    type: glad
    vargs:
      global_dropout: 0.2
      local_dropout: 0.2
      separate_gating: false
      rnn_global: &rnn
        type: bilstm
        vargs:
          num_layers: 1
          pack: true
          dropout: 0.0
      rnn_local: *rnn
