type: generic
vargs:
  word_dim: 700
  hidden_dim: 400
  word_emb_dropout: 0.1
  word_encoder:
    type: composite
    vargs:
      first_dim: 300
      second_dim: 400
      first:
        type: vzhong-embeddings
        vargs:
          freeze: true
          cls_name: GloveEmbedding
          default: zero
      second:
        type: composite
        vargs:
          first_dim: 300
          second_dim: 100
          first:
            type: fasttext
            vargs:
              freeze: true
              fasttext_path: third_party/fasttext/fasttext  # compile this first
              model_path: /home/kani/datasets/fasttext/cc.en.300.bin  # download and specify model_path
          second:
            type: vzhong-embeddings
            vargs:
              freeze: true
              cls_name: KazumaCharEmbedding
              default: zero
  dst_encoder:
    type: glad-star
    vargs:
      num_heads: 10
      att_dim: 400
      global_dropout: 0.2
      local_dropout: 0.2
      separate_gating: true
      rnn_global: &rnn
        type: bilstm
        vargs:
          num_layers: 1
          pack: true
          dropout: 0.2
      rnn_local: *rnn
